backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Άρθρα (HTML)"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    frontmatter_delimiter: ["<!--", "-->"]
    editor: { preview: false }
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Περιεχόμενο (HTML)", name: "body", widget: "text" }
